version: '3.8'

services:
  # 1. DATABASE CONTAINER
  db: 
    image: postgres:16 
    container_name: postgres_db
    environment: 
      POSTGRES_DB: todos_db 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: Apple05130218!
    ports: 
      - "5432:5432" 
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql 

  # 2. BACKEND CONTAINER
  backend:
    build: ./backend # Looks inside /backend to run its Dockerfile
    container_name: express_backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db # Service name matches database container above
      DB_USER: postgres
      DB_PASSWORD: 05130218 
      DB_NAME: todos_db
    depends_on:
      - db

  # 3. FRONTEND CONTAINER
  frontend:
    build: ./frontend # Looks inside /frontend to run its Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173" # Exposes Vite's default dev port to your PC
    environment:
      # Tells your React components where your Express server is running locally
      VITE_API_URL: http://localhost:3000
    depends_on:
      - backend

volumes: 
  pgdata:
