CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN DEFAULT false,
  color TEXT DEFAULT 'yellow',
  status TEXT DEFAULT 'empty',
  tasks TEXT DEFAULT '[]',
  x NUMERIC DEFAULT 100,
  y NUMERIC DEFAULT 100,
  width NUMERIC DEFAULT 160,
  height NUMERIC DEFAULT 160,
  created_at TIMESTAMP DEFAULT NOW()
);